// This file will be auto-generated by Supabase CLI
// Run: npm run generate-types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // Tables will be defined here after running migrations
    };
    Views: {
      // Views will be defined here
    };
    Functions: {
      // Functions will be defined here
    };
    Enums: {
      // Enums will be defined here
    };
  };
}
